const countries = [
  { code: 'AF', name: { en: 'Afghanistan', uk: 'Афганістан' } },
  { code: 'AL', name: { en: 'Albania', uk: 'Албанія' } },
  { code: 'DZ', name: { en: 'Algeria', uk: 'Алжир' } },
  { code: 'AD', name: { en: 'Andorra', uk: 'Андорра' } },
  { code: 'AO', name: { en: 'Angola', uk: 'Ангола' } },
  { code: 'AR', name: { en: 'Argentina', uk: 'Аргентина' } },
  { code: 'AM', name: { en: 'Armenia', uk: 'Вірменія' } },
  { code: 'AU', name: { en: 'Australia', uk: 'Австралія' } },
  { code: 'AT', name: { en: 'Austria', uk: 'Австрія' } },
  { code: 'AZ', name: { en: 'Azerbaijan', uk: 'Азербайджан' } },
  { code: 'BS', name: { en: 'Bahamas', uk: 'Багами' } },
  { code: 'BH', name: { en: 'Bahrain', uk: 'Бахрейн' } },
  { code: 'BD', name: { en: 'Bangladesh', uk: 'Бангладеш' } },
  { code: 'BB', name: { en: 'Barbados', uk: 'Барбадос' } },
  { code: 'BY', name: { en: 'Belarus', uk: 'Білорусь' } },
  { code: 'BE', name: { en: 'Belgium', uk: 'Бельгія' } },
  { code: 'BZ', name: { en: 'Belize', uk: 'Беліз' } },
  { code: 'BJ', name: { en: 'Benin', uk: 'Бенін' } },
  { code: 'BT', name: { en: 'Bhutan', uk: 'Бутан' } },
  { code: 'BO', name: { en: 'Bolivia', uk: 'Болівія' } },
  { code: 'BA', name: { en: 'Bosnia and Herzegovina', uk: 'Боснія і Герцеговина' } },
  { code: 'BW', name: { en: 'Botswana', uk: 'Ботсвана' } },
  { code: 'BR', name: { en: 'Brazil', uk: 'Бразилія' } },
  { code: 'BN', name: { en: 'Brunei', uk: 'Бруней' } },
  { code: 'BG', name: { en: 'Bulgaria', uk: 'Болгарія' } },
  { code: 'BF', name: { en: 'Burkina Faso', uk: 'Буркіна-Фасо' } },
  { code: 'BI', name: { en: 'Burundi', uk: 'Бурунді' } },
  { code: 'CV', name: { en: 'Cabo Verde', uk: 'Кабо-Верде' } },
  { code: 'KH', name: { en: 'Cambodia', uk: 'Камбоджа' } },
  { code: 'CM', name: { en: 'Cameroon', uk: 'Камерун' } },
  { code: 'CA', name: { en: 'Canada', uk: 'Канада' } },
  { code: 'CF', name: { en: 'Central African Republic', uk: 'Центральноафриканська Республіка' } },
  { code: 'TD', name: { en: 'Chad', uk: 'Чад' } },
  { code: 'CL', name: { en: 'Chile', uk: 'Чилі' } },
  { code: 'CN', name: { en: 'China', uk: 'Китай' } },
  { code: 'CO', name: { en: 'Colombia', uk: 'Колумбія' } },
  { code: 'KM', name: { en: 'Comoros', uk: 'Комори' } },
  { code: 'CG', name: { en: 'Congo', uk: 'Конго' } },
  { code: 'CR', name: { en: 'Costa Rica', uk: 'Коста-Рика' } },
  { code: 'HR', name: { en: 'Croatia', uk: 'Хорватія' } },
  { code: 'CU', name: { en: 'Cuba', uk: 'Куба' } },
  { code: 'CY', name: { en: 'Cyprus', uk: 'Кіпр' } },
  { code: 'CZ', name: { en: 'Czech Republic', uk: 'Чехія' } },
  { code: 'DK', name: { en: 'Denmark', uk: 'Данія' } },
  { code: 'DJ', name: { en: 'Djibouti', uk: 'Джибуті' } },
  { code: 'DM', name: { en: 'Dominica', uk: 'Домініка' } },
  { code: 'DO', name: { en: 'Dominican Republic', uk: 'Домініканська Республіка' } },
  { code: 'EC', name: { en: 'Ecuador', uk: 'Еквадор' } },
  { code: 'EG', name: { en: 'Egypt', uk: 'Єгипет' } },
  { code: 'SV', name: { en: 'El Salvador', uk: 'Сальвадор' } },
  { code: 'GQ', name: { en: 'Equatorial Guinea', uk: 'Екваторіальна Гвінея' } },
  { code: 'ER', name: { en: 'Eritrea', uk: 'Еритрея' } },
  { code: 'EE', name: { en: 'Estonia', uk: 'Естонія' } },
  { code: 'SZ', name: { en: 'Eswatini', uk: 'Есватіні' } },
  { code: 'ET', name: { en: 'Ethiopia', uk: 'Ефіопія' } },
  { code: 'FJ', name: { en: 'Fiji', uk: 'Фіджі' } },
  { code: 'FI', name: { en: 'Finland', uk: 'Фінляндія' } },
  { code: 'FR', name: { en: 'France', uk: 'Франція' } },
  { code: 'GA', name: { en: 'Gabon', uk: 'Габон' } },
  { code: 'GM', name: { en: 'Gambia', uk: 'Гамбія' } },
  { code: 'GE', name: { en: 'Georgia', uk: 'Грузія' } },
  { code: 'DE', name: { en: 'Germany', uk: 'Німеччина' } },
  { code: 'GH', name: { en: 'Ghana', uk: 'Гана' } },
  { code: 'GR', name: { en: 'Greece', uk: 'Греція' } },
  { code: 'GD', name: { en: 'Grenada', uk: 'Гренада' } },
  { code: 'GT', name: { en: 'Guatemala', uk: 'Гватемала' } },
  { code: 'GN', name: { en: 'Guinea', uk: 'Гвінея' } },
  { code: 'GW', name: { en: 'Guinea-Bissau', uk: 'Гвінея-Бісау' } },
  { code: 'GY', name: { en: 'Guyana', uk: 'Гаяна' } },
  { code: 'HT', name: { en: 'Haiti', uk: 'Гаїті' } },
  { code: 'HN', name: { en: 'Honduras', uk: 'Гондурас' } },
  { code: 'HU', name: { en: 'Hungary', uk: 'Угорщина' } },
  { code: 'IS', name: { en: 'Iceland', uk: 'Ісландія' } },
  { code: 'IN', name: { en: 'India', uk: 'Індія' } },
  { code: 'ID', name: { en: 'Indonesia', uk: 'Індонезія' } },
  { code: 'IR', name: { en: 'Iran', uk: 'Іран' } },
  { code: 'IQ', name: { en: 'Iraq', uk: 'Ірак' } },
  { code: 'IE', name: { en: 'Ireland', uk: 'Ірландія' } },
  { code: 'IL', name: { en: 'Israel', uk: 'Ізраїль' } },
  { code: 'IT', name: { en: 'Italy', uk: 'Італія' } },
  { code: 'JM', name: { en: 'Jamaica', uk: 'Ямайка' } },
  { code: 'JP', name: { en: 'Japan', uk: 'Японія' } },
  { code: 'JO', name: { en: 'Jordan', uk: 'Йорданія' } },
  { code: 'KZ', name: { en: 'Kazakhstan', uk: 'Казахстан' } },
  { code: 'KE', name: { en: 'Kenya', uk: 'Кенія' } },
  { code: 'KI', name: { en: 'Kiribati', uk: 'Кірибаті' } },
  { code: 'KP', name: { en: 'North Korea', uk: 'Північна Корея' } },
  { code: 'KR', name: { en: 'South Korea', uk: 'Південна Корея' } },
  { code: 'KW', name: { en: 'Kuwait', uk: 'Кувейт' } },
  { code: 'KG', name: { en: 'Kyrgyzstan', uk: 'Киргизстан' } },
  { code: 'LA', name: { en: 'Laos', uk: 'Лаос' } },
  { code: 'LV', name: { en: 'Latvia', uk: 'Латвія' } },
  { code: 'LB', name: { en: 'Lebanon', uk: 'Ліван' } },
  { code: 'LS', name: { en: 'Lesotho', uk: 'Лесото' } },
  { code: 'LR', name: { en: 'Liberia', uk: 'Ліберія' } },
  { code: 'LY', name: { en: 'Libya', uk: 'Лівія' } },
  { code: 'LI', name: { en: 'Liechtenstein', uk: 'Ліхтенштейн' } },
  { code: 'LT', name: { en: 'Lithuania', uk: 'Литва' } },
  { code: 'LU', name: { en: 'Luxembourg', uk: 'Люксембург' } },
  { code: 'MG', name: { en: 'Madagascar', uk: 'Мадагаскар' } },
  { code: 'MW', name: { en: 'Malawi', uk: 'Малаві' } },
  { code: 'MY', name: { en: 'Malaysia', uk: 'Малайзія' } },
  { code: 'MV', name: { en: 'Maldives', uk: 'Мальдіви' } },
  { code: 'ML', name: { en: 'Mali', uk: 'Малі' } },
  { code: 'MT', name: { en: 'Malta', uk: 'Мальта' } },
  { code: 'MH', name: { en: 'Marshall Islands', uk: 'Маршаллові Острови' } },
  { code: 'MR', name: { en: 'Mauritania', uk: 'Мавританія' } },
  { code: 'MU', name: { en: 'Mauritius', uk: 'Маврикій' } },
  { code: 'MX', name: { en: 'Mexico', uk: 'Мексика' } },
  { code: 'FM', name: { en: 'Micronesia', uk: 'Мікронезія' } },
  { code: 'MD', name: { en: 'Moldova', uk: 'Молдова' } },
  { code: 'MC', name: { en: 'Monaco', uk: 'Монако' } },
  { code: 'MN', name: { en: 'Mongolia', uk: 'Монголія' } },
  { code: 'ME', name: { en: 'Montenegro', uk: 'Чорногорія' } },
  { code: 'MA', name: { en: 'Morocco', uk: 'Марокко' } },
  { code: 'MZ', name: { en: 'Mozambique', uk: 'Мозамбік' } },
  { code: 'MM', name: { en: 'Myanmar', uk: 'М’янма' } },
  { code: 'NA', name: { en: 'Namibia', uk: 'Намібія' } },
  { code: 'NR', name: { en: 'Nauru', uk: 'Науру' } },
  { code: 'NP', name: { en: 'Nepal', uk: 'Непал' } },
  { code: 'NL', name: { en: 'Netherlands', uk: 'Нідерланди' } },
  { code: 'NZ', name: { en: 'New Zealand', uk: 'Нова Зеландія' } },
  { code: 'NI', name: { en: 'Nicaragua', uk: 'Нікарагуа' } },
  { code: 'NE', name: { en: 'Niger', uk: 'Нігер' } },
  { code: 'NG', name: { en: 'Nigeria', uk: 'Нігерія' } },
  { code: 'NO', name: { en: 'Norway', uk: 'Норвегія' } },
  { code: 'OM', name: { en: 'Oman', uk: 'Оман' } },
  { code: 'PK', name: { en: 'Pakistan', uk: 'Пакистан' } },
  { code: 'PW', name: { en: 'Palau', uk: 'Палау' } },
  { code: 'PA', name: { en: 'Panama', uk: 'Панама' } },
  { code: 'PG', name: { en: 'Papua New Guinea', uk: 'Папуа-Нова Гвінея' } },
  { code: 'PY', name: { en: 'Paraguay', uk: 'Парагвай' } },
  { code: 'PE', name: { en: 'Peru', uk: 'Перу' } },
  { code: 'PH', name: { en: 'Philippines', uk: 'Філіппіни' } },
  { code: 'PL', name: { en: 'Poland', uk: 'Польща' } },
  { code: 'PT', name: { en: 'Portugal', uk: 'Португалія' } },
  { code: 'QA', name: { en: 'Qatar', uk: 'Катар' } },
  { code: 'RO', name: { en: 'Romania', uk: 'Румунія' } },
  { code: 'RU', name: { en: 'Russia', uk: 'Росія' } },
  { code: 'RW', name: { en: 'Rwanda', uk: 'Руанда' } },
  { code: 'KN', name: { en: 'Saint Kitts and Nevis', uk: 'Сент-Кітс і Невіс' } },
  { code: 'LC', name: { en: 'Saint Lucia', uk: 'Сент-Люсія' } },
  { code: 'VC', name: { en: 'Saint Vincent and the Grenadines', uk: 'Сент-Вінсент і Гренадини' } },
  { code: 'WS', name: { en: 'Samoa', uk: 'Самоа' } },
  { code: 'SM', name: { en: 'San Marino', uk: 'Сан-Марино' } },
  { code: 'ST', name: { en: 'Sao Tome and Principe', uk: 'Сан-Томе і Принсіпі' } },
  { code: 'SA', name: { en: 'Saudi Arabia', uk: 'Саудівська Аравія' } },
  { code: 'SN', name: { en: 'Senegal', uk: 'Сенегал' } },
  { code: 'RS', name: { en: 'Serbia', uk: 'Сербія' } },
  { code: 'SC', name: { en: 'Seychelles', uk: 'Сейшели' } },
  { code: 'SL', name: { en: 'Sierra Leone', uk: 'Сьєрра-Леоне' } },
  { code: 'SG', name: { en: 'Singapore', uk: 'Сінгапур' } },
  { code: 'SK', name: { en: 'Slovakia', uk: 'Словаччина' } },
  { code: 'SI', name: { en: 'Slovenia', uk: 'Словенія' } },
  { code: 'SB', name: { en: 'Solomon Islands', uk: 'Соломонові Острови' } },
  { code: 'SO', name: { en: 'Somalia', uk: 'Сомалі' } },
  { code: 'ZA', name: { en: 'South Africa', uk: 'Південна Африка' } },
  { code: 'SS', name: { en: 'South Sudan', uk: 'Південний Судан' } },
  { code: 'ES', name: { en: 'Spain', uk: 'Іспанія' } },
  { code: 'LK', name: { en: 'Sri Lanka', uk: 'Шрі-Ланка' } },
  { code: 'SD', name: { en: 'Sudan', uk: 'Судан' } },
  { code: 'SR', name: { en: 'Suriname', uk: 'Суринам' } },
  { code: 'SE', name: { en: 'Sweden', uk: 'Швеція' } },
  { code: 'CH', name: { en: 'Switzerland', uk: 'Швейцарія' } },
  { code: 'SY', name: { en: 'Syria', uk: 'Сирія' } },
  { code: 'TJ', name: { en: 'Tajikistan', uk: 'Таджикистан' } },
  { code: 'TZ', name: { en: 'Tanzania', uk: 'Танзанія' } },
  { code: 'TH', name: { en: 'Thailand', uk: 'Таїланд' } },
  { code: 'TL', name: { en: 'Timor-Leste', uk: 'Тимор-Лешті' } },
  { code: 'TG', name: { en: 'Togo', uk: 'Того' } },
  { code: 'TO', name: { en: 'Tonga', uk: 'Тонга' } },
  { code: 'TT', name: { en: 'Trinidad and Tobago', uk: 'Тринідад і Тобаго' } },
  { code: 'TN', name: { en: 'Tunisia', uk: 'Туніс' } },
  { code: 'TR', name: { en: 'Turkey', uk: 'Туреччина' } },
  { code: 'TM', name: { en: 'Turkmenistan', uk: 'Туркменістан' } },
  { code: 'TV', name: { en: 'Tuvalu', uk: 'Тувалу' } },
  { code: 'UG', name: { en: 'Uganda', uk: 'Уганда' } },
  { code: 'UA', name: { en: 'Ukraine', uk: 'Україна' } },
  { code: 'AE', name: { en: 'United Arab Emirates', uk: 'Об’єднані Арабські Емірати' } },
  { code: 'GB', name: { en: 'United Kingdom', uk: 'Велика Британія' } },
  { code: 'US', name: { en: 'United States', uk: 'Сполучені Штати' } },
  { code: 'UY', name: { en: 'Uruguay', uk: 'Уругвай' } },
  { code: 'UZ', name: { en: 'Uzbekistan', uk: 'Узбекистан' } },
  { code: 'VU', name: { en: 'Vanuatu', uk: 'Вануату' } },
  { code: 'VE', name: { en: 'Venezuela', uk: 'Венесуела' } },
  { code: 'VN', name: { en: 'Vietnam', uk: 'В’єтнам' } },
  { code: 'YE', name: { en: 'Yemen', uk: 'Ємен' } },
  { code: 'ZM', name: { en: 'Zambia', uk: 'Замбія' } },
  { code: 'ZW', name: { en: 'Zimbabwe', uk: 'Зімбабве' } },
];

export default countries;